### ISSUE TITLE
Suggestion] Why don't we makes fibo.py

### ISSUE THREAD

**Issue by bini-kim** [bini-kim/branch_practice#1]
Fibonacci Sequence를 구하는 파이썬 스크립트를 만들고 싶어요
만들어 주실거죠?(미리 감사합니다!)

## Tasks

- [ ] Fibo with Recursion
- [ ] Fibo with Memoization
- [ ] Fibo with binet's formula

$$F_n=\dfrac{\left(\dfrac{1+\sqrt{5}}{2}\right)^n-\left(\dfrac{1-\sqrt{5}}{2}\right)^n}{\sqrt{5}}$$
